name: GitOps Terraform Apply (Local)

on:
  push:
    branches:
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: prj1
        run: terraform init

      - name: Terraform Validate
        working-directory: prj1
        run: terraform validate

      - name: Terraform Plan
        working-directory: prj1
        run: terraform plan

      - name: Terraform Apply
        working-directory: prj1
        run: terraform apply -auto-approve
